---

- name: "configuration play" 
  hosts: web
  user: ubuntu
  become: true
  become_method: sudo
  become_user: root  
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

    - name: "install python for Ansible."
      command: |
        yum update -y
        yum upgrade -y
        yum install python3.9 -y
        update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.9 1

  roles:
    - deploy
