---

- name: 'update upgrade packages.'
  become: true
  yum:
    upgrade: yes
    

- name: remove unneeded deps
  become: true
  yum:
    autoremove: yes

- name: install deps
  become: true
  yum:
    name: ['nodejs', 'npm']
    state: latest
    update_cache: yes

- name: install pm2
  become: true
  npm:
    name: pm2
    global: yes
    state: latest
    production: yes

