---

- name: "update yum packages."
  become: true
  yum:
    update_cache: yes


- name: "install NPM repo"
  become: true
  shell: curl -sL https://rpm.nodesource.com/setup_10.x | bash -
    

- name: "install NPM dependencies."
  become: true
  yum:
    name: 
      - nodejs
      - gcc-c++
      - make
    state: latest
    update_cache: yes

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

